### PR TITLE
add lfgruv theme

### PR DESCRIPTION
**Pull request by boppyt**
This is a port of https://github.com/jayden-chan/gruvbox/blob/bec6632fb0453405677dfc3cca427fa4e486d09c/colors/gruvbox.vim#L88 in nvim-base16.

v2

### CODE REVIEW

**Comment by boppyt** [comment]
oops sorry, weird clipboard.

**Comment by boppyt** [comment]
here's what it looks like @siduck76 :

image

**Comment by boppyt** [comment]
Wait, I do see some wrong highlights. let me fix that rq.

**Comment by boppyt** [comment]
Should be good to go now, @siduck76

**Comment by boppyt** [comment]
image
This is how it looks now

**Comment by siduck76** [comment]
nice , could you add one theme for nvchad ui too? in lua/colors/themes/lfgruv.lua

**Comment by boppyt** [comment]
added it in NvChad repo, @siduck76 
NvChad/NvChad#442

**Comment by siduck76** [comment]
@boppyt you can fix some colors if you want to : 

check https://nvchad.github.io/contribute#how-to-submit-themes

**Comment by boppyt** [comment]
Will fix that asap (probs tomorrow).

**Pull request merged**
