### PR TITLE
add nightlamp theme

### PR DESCRIPTION
**Pull request by boppyt**
mix of multiple themes to fit my preference.
been using this in my fork for few months.

image

### CODE REVIEW

**Comment by siduck** [comment]
did you follow our theme contributing guide? if not then i'll have to fix this theme into 'nightchad' :rofl:

**Comment by boppyt** [comment]
Hmm, I don't see anything that enforces name changes.
But I could change it, if that fits the chad ecosystem more.

**Comment by boppyt** [comment]
@siduck chadified the name.
do you mind giving me a link that encourages theme names to be -chad?

p.s squash please

**Comment by siduck** [comment]
> Hmm, I don't see anything that enforces name changes. But I could change it, if that fits the chad ecosystem more.

noooo i didnt mean that! most themes in the PR's we've got until now had many degraded colors so I had to edit them myself which was annoying so I add 'chad' in their name xd

**Comment by siduck** [comment]
if your theme's fine and doesnt need any change from my side then it will not have the chad name!

**Comment by boppyt** [comment]
Ah I see, I guess I can just keep its original name since I'd say it's fine.

Mostly because I made this theme (although it's just a mix of themes with tweaks) lol

**Pull request merged**
