### PR TITLE
Added "onebright" theme

### PR DESCRIPTION
**Pull request by phanlong2811**
image
It's pretty much like onedark but it's brighter, I got it from the [original repo](https://github.com/norcalli/nvim-base16.lua/blob/b336f40462b3ca1ad16a17c195b83731a2942d9a/lua/base16.lua#L867-L872). I really like it <3

### CODE REVIEW

**Comment by phanlong2811** [comment]
image

**Comment by siduck** [comment]
ay i dont think this is material og theme!

**Comment by siduck** [comment]
this is material 

https://material-theme.site/
https://github.com/equinusocio/material-theme

**Comment by phanlong2811** [comment]
So can I call it "onedark-brighter", can you add it to the repo? I will push some new commits now

**Comment by siduck** [comment]
change the name to onebright

**Comment by phanlong2811** [comment]
Changed! @siduck

**Pull request merged**
