### PR TITLE
Added vscode theme

### PR DESCRIPTION
**Pull request by Johnsiras**
Added vscode theme, just mention me if there are any problems and i will fix it!

Got this from: https://github.com/Mofiqul/vscode.nvim

### CODE REVIEW

**Comment by Johnsiras** [comment]
(Idk how to test it, but if there's any issues after merging i'll fix it)

**Comment by siduck** [comment]
test it locally or replace this     with yours 
image

**Comment by Johnsiras** [comment]
wait wdym by, "test it locally or replace this with yours"?

Sorry i don't understand

**Comment by Johnsiras** [comment]
It's kinda off but fixing these colors later after finishing my tasks 👀 

wezterm-gui_65jIhdYtg1

**Comment by Johnsiras** [comment]
@siduck how's this?

**Comment by Johnsiras** [comment]
wezterm-gui_COSDwhKVg0

**Comment by siduck** [comment]
> wezterm-gui_hpUTijwdtE

looks great! Can you open the same file in vscode and compare side by side? :thinking:

**Comment by Johnsiras** [comment]
> > wezterm-gui_hpUTijwdtE
> 
> looks great! Can you open the same file in vscode and compare side by side? 🤔

Here :)
5yk1GdyV2s

**Comment by Johnsiras** [comment]
btw both of it have (rainbow brackets plugin) thing so they have colors on brackets

**Comment by siduck** [comment]
> btw both of it have (rainbow brackets plugin) thing installed so they have colors on brackets

conditionals and loops look bad on nvchad (btw our issue, your theme is nice). Wait for a while then I'll add some functionality to override tshighlights within base16 theme so we could match the OG themes in nvchad and make it more prettier :D

**Comment by Johnsiras** [comment]
Thanks! 👍

**Comment by Johnsiras** [comment]
Can't make a new request

**Comment by Johnsiras** [comment]
I'll close this for now, i can't create a new request for moonlight theme :/

i'll open this after you add some functionality thing your saying

**Pull request closed without merging**
