### PR TITLE
Made tweaks to the original theme, and actually implemented the HL theme

### PR DESCRIPTION
**Pull request by Collatz124**
Hey, this will hopefully be the final pull request (I FINALLY figured out how to set the theme locally, which made everything alot easier :sweat_smile: )

Screenshot of the final product

Screenshot from 2021-12-13 20-03-38

\- Martin

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
@Collatz124 there's something weird with this theme , the statusline bg looks odd and bufferline active bar too

**Comment by siduck** [comment]
nvm fixed em https://github.com/NvChad/nvim-base16.lua/commit/7c48964bcee39d12e1c23b87943822b9812d10de

**Comment by Collatz124** [comment]
What do you mean fixed it? you just reverted pretty much all of my changes.

**Comment by siduck** [comment]
> What do you mean fixed it? you just reverted pretty much all of my changes.

image

statuslinebg is usually at least 5% lighter than black 

- your black color should be equal to base00 but it wasnt :/

image

**Comment by siduck** [comment]
many dark colors are based and dependent on black so  you must keep it = base00 !!!

**Comment by siduck** [comment]
bufferline bg is barely visible 

image


active buffer = black color :/

**Comment by Collatz124** [comment]
Fair ill take a look, should have read the docs more carefully :sweat_smile:, what about the actual colors in the config?

**Comment by siduck** [comment]
> Fair ill take a look, should have read the docs more carefully sweat_smile, what about the actual colors in the config?

which config

**Comment by Collatz124** [comment]
The hl config

**Comment by siduck** [comment]
oh yea

**Comment by siduck** [comment]
image

ngl it looks better than the onedark theme

**Comment by Collatz124** [comment]
> 

Thank you man, am i free to pick the colors, which arent specifically specified in the documentation ([https://nvchad.github.io/contribute](url))?

**Comment by siduck** [comment]
> > 
> 
> Thank you man, am i free to pick the colors, which arent specifically specified in the documentation ([https://nvchad.github.io/contribute](url))?

yes but make sure they match with your theme!

**Comment by Collatz124** [comment]
I had a change to look over the changes that you made, the only one i would like reverted is the purple, the others i can live with, so i'm not gonna bother with a yet another pull request :smile: , thank you for your contribution, love the work that you guys do.

-- Martin

**Comment by siduck** [comment]
> I had a change to look over the changes that you made, the only one i would like reverted is the purple, the others i can live with, so i'm not gonna bother with a yet another pull request smile , thank you for your contribution, love the work that you guys do.
> 
> -- Martin

hmm the purple color looks fine! it must be 20% lighter than darker_purple

**Pull request merged**
