### PR TITLE
One Monokai Theme

### PR DESCRIPTION
**Pull request by Collatz124**
Hello, 

I propose adding the following theme (One Monokai) to the library.

Inspired by
[https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai](url)

**PS:** sorry for the lack of screenshots, weren't proficient enough in Lua / Vim to actually enable the theme, from my own configuration, yikes :rofl:

### CODE REVIEW

**Comment by siduck** [comment]
did you follow our theme guide?

**Comment by Collatz124** [comment]
Yes, i did my best, however i was a little confused on what to name the files...

**Comment by siduck** [comment]
> Yes, i did my best, however i was a little confused on what to name the files...

can you name it to monekai? :D

**Comment by Collatz124** [comment]
> > Yes, i did my best, however i was a little confused on what to name the files...
> 
> can you name it to monekai? :D

Done :)

**Pull request merged**
