### PR TITLE
Added Aquarium

### PR DESCRIPTION
**Pull request by FrenzyExists**
So, I added aquarium here, as I was notified to add the theme here. Aquarium is a dark, yet vibrant here. Hope you guys like it!

### CODE REVIEW

**Comment by siduck76** [comment]
@FrenzyExists thanks for this! btw remove the "#" from the colors or the theme will crash xD

**Comment by FrenzyExists** [comment]
On it

**Comment by FrenzyExists** [comment]
Currently fixing the base names, I didn't realized that the naming convection between NvChad and the base-16

**Comment by siduck76** [comment]
> Currently fixing the base names, I didn't realized that the naming convection between NvChad and the base-16

https://github.com/NvChad/NvChad/wiki/Themes , check where the colors are used in highlights.lua . just do a quick search with /

**Comment by FrenzyExists** [comment]
On it :+1:

**Comment by FrenzyExists** [comment]
Fixed, I didn't knew there was a base-16 standard before. I think I'll reformat my theme repo following the base-16 standard. Currently, aquarium (the vim colorscheme) has a base-14. Quite glad I decided to work a theme on this repo, now the colorscheme has two new colors! Anyway, does this commit pass?

**Pull request merged**
