### PR TITLE
uwu: changes into bg color

### PR DESCRIPTION
**Pull request by Mangeshrex**
I felt like the background color was way too darker and was like similar to black. So, i have changed its background to something lighter which looks good to me

### CODE REVIEW

**Comment by siduck76** [comment]
just changing the bg wont work!! rest of the dark colors are dependent on the previous bg color :/

**Comment by Mangeshrex** [comment]
So, do you mean that changing the background has messed up with the other 7 colors ? wait lemme show you

Fri Sep 24 08:56:27 PM IST 2021

Fri Sep 24 03:45:02 PM IST 2021

**Comment by siduck76** [comment]
yes it will mess up , for example black2 is 6% lightened color of black color in hl_themes , but u changed that! and there are many colors like that , i will soon add wiki for submitting themes so watchout

**Comment by Mangeshrex** [comment]
bruh :/ I in hl_themes other than darker_black black (nvim bg here) and ig statusline i havent changed any other colors here. If you're talking of themes/uwu-base16.lua then i can find a even more lighter background. but this seems good to me

**Comment by Mangeshrex** [comment]
? No reply

**Comment by Mangeshrex** [comment]
Hey can you give a review now?

**Review by siduck76 — APPROVED** [review]

**Pull request merged**
